### ISSUE TITLE
No content on live site

### ISSUE THREAD

**Issue by dwalter0** [infosecstreams/infosecstreams.github.io#94]
Seems like the live site doesn't have any content anymore https://infosecstreams.github.io/. It shows the header as before but the list of all the streamers is gone.

**Comment by goproslowyo** [comment]
Hey @dwalter0 -- thanks so much for reporting this. This is a known bug that I haven't had time to track down yet.

I'm not 100% sure what causes it but I also want to re-write a bunch of the Python and Golang code that runs the site into a new code base.

I'll keep this open as a means of tracking that work.

**Comment by goproslowyo** [comment]
@dwalter0 I believe I squashed this bug. Can you please let me know if this turns up again? Thank you for reporting the issue!

Essentially we now [use this](github.com/infosecstreams/secinfo) combined [with this](https://github.com/infosecstreams/StreamStatus) instead of the [really janky python](https://github.com/infosecstreams/infosecstreams.github.io/blob/f42cc1c331910b2e78abacb68836406bfd40c328/GetTwoWeekStreamActivity.py) script.
